name: Copy All Files via SSH 

on:
  push:
    branches:
      - main

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install sshpass
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      # Copy all files from the repository to the remote server using password authentication
      - name: Copy all files to remote server using password
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -r . root@${{ secrets.REMOTE_HOST }}:/tmp
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
